package com.intermap.content.audit.entity;

import java.util.Date;

public class CodeApp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_app.id
     *
     * @mbg.generated
     */
    private Short id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_app.app_id
     *
     * @mbg.generated
     */
    private String appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_app.app_name
     *
     * @mbg.generated
     */
    private String appName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_app.platform_id
     *
     * @mbg.generated
     */
    private Short platformId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_app.callback_url
     *
     * @mbg.generated
     */
    private String callbackUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_app.policy_template_id
     *
     * @mbg.generated
     */
    private Short policyTemplateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_app.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_app.created
     *
     * @mbg.generated
     */
    private Date created;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_app.id
     *
     * @return the value of code_app.id
     *
     * @mbg.generated
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_app.id
     *
     * @param id the value for code_app.id
     *
     * @mbg.generated
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_app.app_id
     *
     * @return the value of code_app.app_id
     *
     * @mbg.generated
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_app.app_id
     *
     * @param appId the value for code_app.app_id
     *
     * @mbg.generated
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_app.app_name
     *
     * @return the value of code_app.app_name
     *
     * @mbg.generated
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_app.app_name
     *
     * @param appName the value for code_app.app_name
     *
     * @mbg.generated
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_app.platform_id
     *
     * @return the value of code_app.platform_id
     *
     * @mbg.generated
     */
    public Short getPlatformId() {
        return platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_app.platform_id
     *
     * @param platformId the value for code_app.platform_id
     *
     * @mbg.generated
     */
    public void setPlatformId(Short platformId) {
        this.platformId = platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_app.callback_url
     *
     * @return the value of code_app.callback_url
     *
     * @mbg.generated
     */
    public String getCallbackUrl() {
        return callbackUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_app.callback_url
     *
     * @param callbackUrl the value for code_app.callback_url
     *
     * @mbg.generated
     */
    public void setCallbackUrl(String callbackUrl) {
        this.callbackUrl = callbackUrl == null ? null : callbackUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_app.policy_template_id
     *
     * @return the value of code_app.policy_template_id
     *
     * @mbg.generated
     */
    public Short getPolicyTemplateId() {
        return policyTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_app.policy_template_id
     *
     * @param policyTemplateId the value for code_app.policy_template_id
     *
     * @mbg.generated
     */
    public void setPolicyTemplateId(Short policyTemplateId) {
        this.policyTemplateId = policyTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_app.description
     *
     * @return the value of code_app.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_app.description
     *
     * @param description the value for code_app.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_app.created
     *
     * @return the value of code_app.created
     *
     * @mbg.generated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_app.created
     *
     * @param created the value for code_app.created
     *
     * @mbg.generated
     */
    public void setCreated(Date created) {
        this.created = created;
    }
}