package com.intermap.content.audit.entity;

import java.util.Date;

public class CodePlatform {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_platform.id
     *
     * @mbg.generated
     */
    private Short id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_platform.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_platform.domain
     *
     * @mbg.generated
     */
    private String domain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_platform.sha_key
     *
     * @mbg.generated
     */
    private String shaKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_platform.public_filter_id
     *
     * @mbg.generated
     */
    private String publicFilterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_platform.callback_url
     *
     * @mbg.generated
     */
    private String callbackUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_platform.created
     *
     * @mbg.generated
     */
    private Date created;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_platform.id
     *
     * @return the value of code_platform.id
     *
     * @mbg.generated
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_platform.id
     *
     * @param id the value for code_platform.id
     *
     * @mbg.generated
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_platform.name
     *
     * @return the value of code_platform.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_platform.name
     *
     * @param name the value for code_platform.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_platform.domain
     *
     * @return the value of code_platform.domain
     *
     * @mbg.generated
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_platform.domain
     *
     * @param domain the value for code_platform.domain
     *
     * @mbg.generated
     */
    public void setDomain(String domain) {
        this.domain = domain == null ? null : domain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_platform.sha_key
     *
     * @return the value of code_platform.sha_key
     *
     * @mbg.generated
     */
    public String getShaKey() {
        return shaKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_platform.sha_key
     *
     * @param shaKey the value for code_platform.sha_key
     *
     * @mbg.generated
     */
    public void setShaKey(String shaKey) {
        this.shaKey = shaKey == null ? null : shaKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_platform.public_filter_id
     *
     * @return the value of code_platform.public_filter_id
     *
     * @mbg.generated
     */
    public String getPublicFilterId() {
        return publicFilterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_platform.public_filter_id
     *
     * @param publicFilterId the value for code_platform.public_filter_id
     *
     * @mbg.generated
     */
    public void setPublicFilterId(String publicFilterId) {
        this.publicFilterId = publicFilterId == null ? null : publicFilterId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_platform.callback_url
     *
     * @return the value of code_platform.callback_url
     *
     * @mbg.generated
     */
    public String getCallbackUrl() {
        return callbackUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_platform.callback_url
     *
     * @param callbackUrl the value for code_platform.callback_url
     *
     * @mbg.generated
     */
    public void setCallbackUrl(String callbackUrl) {
        this.callbackUrl = callbackUrl == null ? null : callbackUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_platform.created
     *
     * @return the value of code_platform.created
     *
     * @mbg.generated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_platform.created
     *
     * @param created the value for code_platform.created
     *
     * @mbg.generated
     */
    public void setCreated(Date created) {
        this.created = created;
    }
}