package com.intermap.content.audit.entity;

public class DataResourceKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_resource.data_id
     *
     * @mbg.generated
     */
    private Long dataId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_resource.order
     *
     * @mbg.generated
     */
    private Byte order;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_resource.data_id
     *
     * @return the value of data_resource.data_id
     *
     * @mbg.generated
     */
    public Long getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_resource.data_id
     *
     * @param dataId the value for data_resource.data_id
     *
     * @mbg.generated
     */
    public void setDataId(Long dataId) {
        this.dataId = dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_resource.order
     *
     * @return the value of data_resource.order
     *
     * @mbg.generated
     */
    public Byte getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_resource.order
     *
     * @param order the value for data_resource.order
     *
     * @mbg.generated
     */
    public void setOrder(Byte order) {
        this.order = order;
    }
}