package com.intermap.content.audit.entity;

import com.alibaba.fastjson.JSON;

import java.util.Date;

public class DataRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_record_20190318.data_id
     *
     * @mbg.generated
     */
    private Long dataId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_record_20190318.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_record_20190318.uid
     *
     * @mbg.generated
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_record_20190318.ip
     *
     * @mbg.generated
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_record_20190318.device
     *
     * @mbg.generated
     */
    private String device;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_record_20190318.publish_date
     *
     * @mbg.generated
     */
    private Date publishDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_record_20190318.app_id
     *
     * @mbg.generated
     */
    private Short appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_record_20190318.digest
     *
     * @mbg.generated
     */
    private String digest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_record_20190318.updated
     *
     * @mbg.generated
     */
    private Date updated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_record_20190318.created
     *
     * @mbg.generated
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_record_20190318.version
     *
     * @mbg.generated
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_record_20190318.sys_status
     *
     * @mbg.generated
     */
    private Byte sysStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_record_20190318.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_record_20190318.sys_policy
     *
     * @mbg.generated
     */
    private String sysPolicy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_record_20190318.operator
     *
     * @mbg.generated
     */
    private Integer operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_record_20190318.data_type
     *
     * @mbg.generated
     */
    private Byte dataType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_record_20190318.msg_type
     *
     * @mbg.generated
     */
    private Byte msgType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_record_20190318.nick_name
     *
     * @mbg.generated
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_record_20190318.user_level
     *
     * @mbg.generated
     */
    private Long userLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_record_20190318.extension
     *
     * @mbg.generated
     */
    private String extension;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_record_20190318.data_id
     *
     * @return the value of data_record_20190318.data_id
     *
     * @mbg.generated
     */
    public Long getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_record_20190318.data_id
     *
     * @param dataId the value for data_record_20190318.data_id
     *
     * @mbg.generated
     */
    public void setDataId(Long dataId) {
        this.dataId = dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_record_20190318.id
     *
     * @return the value of data_record_20190318.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_record_20190318.id
     *
     * @param id the value for data_record_20190318.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_record_20190318.uid
     *
     * @return the value of data_record_20190318.uid
     *
     * @mbg.generated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_record_20190318.uid
     *
     * @param uid the value for data_record_20190318.uid
     *
     * @mbg.generated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_record_20190318.ip
     *
     * @return the value of data_record_20190318.ip
     *
     * @mbg.generated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_record_20190318.ip
     *
     * @param ip the value for data_record_20190318.ip
     *
     * @mbg.generated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_record_20190318.device
     *
     * @return the value of data_record_20190318.device
     *
     * @mbg.generated
     */
    public String getDevice() {
        return device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_record_20190318.device
     *
     * @param device the value for data_record_20190318.device
     *
     * @mbg.generated
     */
    public void setDevice(String device) {
        this.device = device == null ? null : device.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_record_20190318.publish_date
     *
     * @return the value of data_record_20190318.publish_date
     *
     * @mbg.generated
     */
    public Date getPublishDate() {
        return publishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_record_20190318.publish_date
     *
     * @param publishDate the value for data_record_20190318.publish_date
     *
     * @mbg.generated
     */
    public void setPublishDate(Date publishDate) {
        this.publishDate = publishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_record_20190318.app_id
     *
     * @return the value of data_record_20190318.app_id
     *
     * @mbg.generated
     */
    public Short getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_record_20190318.app_id
     *
     * @param appId the value for data_record_20190318.app_id
     *
     * @mbg.generated
     */
    public void setAppId(Short appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_record_20190318.digest
     *
     * @return the value of data_record_20190318.digest
     *
     * @mbg.generated
     */
    public String getDigest() {
        return digest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_record_20190318.digest
     *
     * @param digest the value for data_record_20190318.digest
     *
     * @mbg.generated
     */
    public void setDigest(String digest) {
        this.digest = digest == null ? null : digest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_record_20190318.updated
     *
     * @return the value of data_record_20190318.updated
     *
     * @mbg.generated
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_record_20190318.updated
     *
     * @param updated the value for data_record_20190318.updated
     *
     * @mbg.generated
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_record_20190318.created
     *
     * @return the value of data_record_20190318.created
     *
     * @mbg.generated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_record_20190318.created
     *
     * @param created the value for data_record_20190318.created
     *
     * @mbg.generated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_record_20190318.version
     *
     * @return the value of data_record_20190318.version
     *
     * @mbg.generated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_record_20190318.version
     *
     * @param version the value for data_record_20190318.version
     *
     * @mbg.generated
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_record_20190318.sys_status
     *
     * @return the value of data_record_20190318.sys_status
     *
     * @mbg.generated
     */
    public Byte getSysStatus() {
        return sysStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_record_20190318.sys_status
     *
     * @param sysStatus the value for data_record_20190318.sys_status
     *
     * @mbg.generated
     */
    public void setSysStatus(Byte sysStatus) {
        this.sysStatus = sysStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_record_20190318.status
     *
     * @return the value of data_record_20190318.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_record_20190318.status
     *
     * @param status the value for data_record_20190318.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_record_20190318.sys_policy
     *
     * @return the value of data_record_20190318.sys_policy
     *
     * @mbg.generated
     */
    public String getSysPolicy() {
        return sysPolicy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_record_20190318.sys_policy
     *
     * @param sysPolicy the value for data_record_20190318.sys_policy
     *
     * @mbg.generated
     */
    public void setSysPolicy(String sysPolicy) {
        this.sysPolicy = sysPolicy == null ? null : sysPolicy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_record_20190318.operator
     *
     * @return the value of data_record_20190318.operator
     *
     * @mbg.generated
     */
    public Integer getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_record_20190318.operator
     *
     * @param operator the value for data_record_20190318.operator
     *
     * @mbg.generated
     */
    public void setOperator(Integer operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_record_20190318.data_type
     *
     * @return the value of data_record_20190318.data_type
     *
     * @mbg.generated
     */
    public Byte getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_record_20190318.data_type
     *
     * @param dataType the value for data_record_20190318.data_type
     *
     * @mbg.generated
     */
    public void setDataType(Byte dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_record_20190318.msg_type
     *
     * @return the value of data_record_20190318.msg_type
     *
     * @mbg.generated
     */
    public Byte getMsgType() {
        return msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_record_20190318.msg_type
     *
     * @param msgType the value for data_record_20190318.msg_type
     *
     * @mbg.generated
     */
    public void setMsgType(Byte msgType) {
        this.msgType = msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_record_20190318.nick_name
     *
     * @return the value of data_record_20190318.nick_name
     *
     * @mbg.generated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_record_20190318.nick_name
     *
     * @param nickName the value for data_record_20190318.nick_name
     *
     * @mbg.generated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_record_20190318.user_level
     *
     * @return the value of data_record_20190318.user_level
     *
     * @mbg.generated
     */
    public Long getUserLevel() {
        return userLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_record_20190318.user_level
     *
     * @param userLevel the value for data_record_20190318.user_level
     *
     * @mbg.generated
     */
    public void setUserLevel(Long userLevel) {
        this.userLevel = userLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_record_20190318.extension
     *
     * @return the value of data_record_20190318.extension
     *
     * @mbg.generated
     */
    public String getExtension() {
        return extension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_record_20190318.extension
     *
     * @param extension the value for data_record_20190318.extension
     *
     * @mbg.generated
     */
    public void setExtension(String extension) {
        this.extension = extension == null ? null : extension.trim();
    }

    @Override
    public String toString(){
        return JSON.toJSONString(this);
    }
}