package com.intermap.content.audit.entity;

import java.util.Date;

public class DubboFilterConfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dubbofilterconfig.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dubbofilterconfig.interfacename
     *
     * @mbg.generated
     */
    private String interfacename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dubbofilterconfig.method
     *
     * @mbg.generated
     */
    private String method;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dubbofilterconfig.appname
     *
     * @mbg.generated
     */
    private String appname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dubbofilterconfig.namespace
     *
     * @mbg.generated
     */
    private String namespace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dubbofilterconfig.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dubbofilterconfig.operator
     *
     * @mbg.generated
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dubbofilterconfig.updatetime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dubbofilterconfig.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dubbofilterconfig.id
     *
     * @return the value of dubbofilterconfig.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dubbofilterconfig.id
     *
     * @param id the value for dubbofilterconfig.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dubbofilterconfig.interfacename
     *
     * @return the value of dubbofilterconfig.interfacename
     *
     * @mbg.generated
     */
    public String getInterfacename() {
        return interfacename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dubbofilterconfig.interfacename
     *
     * @param interfacename the value for dubbofilterconfig.interfacename
     *
     * @mbg.generated
     */
    public void setInterfacename(String interfacename) {
        this.interfacename = interfacename == null ? null : interfacename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dubbofilterconfig.method
     *
     * @return the value of dubbofilterconfig.method
     *
     * @mbg.generated
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dubbofilterconfig.method
     *
     * @param method the value for dubbofilterconfig.method
     *
     * @mbg.generated
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dubbofilterconfig.appname
     *
     * @return the value of dubbofilterconfig.appname
     *
     * @mbg.generated
     */
    public String getAppname() {
        return appname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dubbofilterconfig.appname
     *
     * @param appname the value for dubbofilterconfig.appname
     *
     * @mbg.generated
     */
    public void setAppname(String appname) {
        this.appname = appname == null ? null : appname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dubbofilterconfig.namespace
     *
     * @return the value of dubbofilterconfig.namespace
     *
     * @mbg.generated
     */
    public String getNamespace() {
        return namespace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dubbofilterconfig.namespace
     *
     * @param namespace the value for dubbofilterconfig.namespace
     *
     * @mbg.generated
     */
    public void setNamespace(String namespace) {
        this.namespace = namespace == null ? null : namespace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dubbofilterconfig.type
     *
     * @return the value of dubbofilterconfig.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dubbofilterconfig.type
     *
     * @param type the value for dubbofilterconfig.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dubbofilterconfig.operator
     *
     * @return the value of dubbofilterconfig.operator
     *
     * @mbg.generated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dubbofilterconfig.operator
     *
     * @param operator the value for dubbofilterconfig.operator
     *
     * @mbg.generated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dubbofilterconfig.updatetime
     *
     * @return the value of dubbofilterconfig.updatetime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dubbofilterconfig.updatetime
     *
     * @param updatetime the value for dubbofilterconfig.updatetime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dubbofilterconfig.createtime
     *
     * @return the value of dubbofilterconfig.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dubbofilterconfig.createtime
     *
     * @param createtime the value for dubbofilterconfig.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}