package com.intermap.content.audit.entity;

public class Plugin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugins.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugins.header
     *
     * @mbg.generated
     */
    private String header;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugins.platform
     *
     * @mbg.generated
     */
    private String platform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugins.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugins.version
     *
     * @mbg.generated
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugins.pluginname
     *
     * @mbg.generated
     */
    private String pluginname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugins.ip
     *
     * @mbg.generated
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugins.servicename
     *
     * @mbg.generated
     */
    private String servicename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugins.namespace
     *
     * @mbg.generated
     */
    private String namespace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugins.timestamp
     *
     * @mbg.generated
     */
    private Long timestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugins.id
     *
     * @return the value of plugins.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugins.id
     *
     * @param id the value for plugins.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugins.header
     *
     * @return the value of plugins.header
     *
     * @mbg.generated
     */
    public String getHeader() {
        return header;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugins.header
     *
     * @param header the value for plugins.header
     *
     * @mbg.generated
     */
    public void setHeader(String header) {
        this.header = header == null ? null : header.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugins.platform
     *
     * @return the value of plugins.platform
     *
     * @mbg.generated
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugins.platform
     *
     * @param platform the value for plugins.platform
     *
     * @mbg.generated
     */
    public void setPlatform(String platform) {
        this.platform = platform == null ? null : platform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugins.type
     *
     * @return the value of plugins.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugins.type
     *
     * @param type the value for plugins.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugins.version
     *
     * @return the value of plugins.version
     *
     * @mbg.generated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugins.version
     *
     * @param version the value for plugins.version
     *
     * @mbg.generated
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugins.pluginname
     *
     * @return the value of plugins.pluginname
     *
     * @mbg.generated
     */
    public String getPluginname() {
        return pluginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugins.pluginname
     *
     * @param pluginname the value for plugins.pluginname
     *
     * @mbg.generated
     */
    public void setPluginname(String pluginname) {
        this.pluginname = pluginname == null ? null : pluginname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugins.ip
     *
     * @return the value of plugins.ip
     *
     * @mbg.generated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugins.ip
     *
     * @param ip the value for plugins.ip
     *
     * @mbg.generated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugins.servicename
     *
     * @return the value of plugins.servicename
     *
     * @mbg.generated
     */
    public String getServicename() {
        return servicename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugins.servicename
     *
     * @param servicename the value for plugins.servicename
     *
     * @mbg.generated
     */
    public void setServicename(String servicename) {
        this.servicename = servicename == null ? null : servicename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugins.namespace
     *
     * @return the value of plugins.namespace
     *
     * @mbg.generated
     */
    public String getNamespace() {
        return namespace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugins.namespace
     *
     * @param namespace the value for plugins.namespace
     *
     * @mbg.generated
     */
    public void setNamespace(String namespace) {
        this.namespace = namespace == null ? null : namespace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugins.timestamp
     *
     * @return the value of plugins.timestamp
     *
     * @mbg.generated
     */
    public Long getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugins.timestamp
     *
     * @param timestamp the value for plugins.timestamp
     *
     * @mbg.generated
     */
    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }
}