package com.intermap.content.audit.dao;

import com.intermap.content.audit.entity.DataResource;
import com.intermap.content.audit.entity.DataResourceKey;

public interface DataResourceDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_resource
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(DataResourceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_resource
     *
     * @mbg.generated
     */
    int insert(DataResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_resource
     *
     * @mbg.generated
     */
    int insertSelective(DataResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_resource
     *
     * @mbg.generated
     */
    DataResource selectByPrimaryKey(DataResourceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_resource
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DataResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_resource
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(DataResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_resource
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DataResource record);
}