package com.intermap.content.audit.dao;

import com.intermap.content.audit.entity.DubboFilterConfig;

public interface DubboFilterConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dubbofilterconfig
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dubbofilterconfig
     *
     * @mbg.generated
     */
    int insert(DubboFilterConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dubbofilterconfig
     *
     * @mbg.generated
     */
    int insertSelective(DubboFilterConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dubbofilterconfig
     *
     * @mbg.generated
     */
    DubboFilterConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dubbofilterconfig
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DubboFilterConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dubbofilterconfig
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DubboFilterConfig record);
}