package com.intermap.content.audit.dao;


import com.intermap.content.audit.entity.Plugin;

import java.util.List;
import java.util.Map;

public interface IPluginDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugins
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    int deleteByPlugin(Plugin record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugins
     *
     * @mbg.generated
     */
    int insert(Plugin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugins
     *
     * @mbg.generated
     */
    int insertSelective(Plugin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugins
     *
     * @mbg.generated
     */
    Plugin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugins
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Plugin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugins
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Plugin record);

    int batchInsertPlugins(Map<String, List<Plugin>> pluginsMap);

    /**
     * @FileName IPluginDao.java
     * @ClassName IPluginDao
     * @MethodName getPlugins
     * @Desc 按时间排序返回前200条插件信息
     * @author zouxiaodong
     * @date 2018/11/15 10:30
     * @Params [Plugin plugin]
     * @return java.util.List<com.mobanker.component.routecenter.service.model.Plugin>
     */
    List<Plugin> getPlugins(Plugin plugin);

}